### ISSUE TITLE
Homework 2 completed

### ISSUE THREAD

**Issue by SofyaMulenok** [SofyaMulenok/homework_week1#13]
I've completed the second homework, details are in the second half of the ReadMe file. Phew!
@DiyahM @Keenahn @LijieZhou

**Comment by DiyahM** [comment]
Looks Good! Curious -- How long did it take you to complete this weeks assignment?

**Comment by SofyaMulenok** [comment]
Thank you @DiyahM! I guess it took about 5 hours (I've tried several different layouts before I found the one I liked).
