### ISSUE TITLE
Homework 4

### ISSUE THREAD

**Issue by SofyaMulenok** [SofyaMulenok/homework_week1#15]
@DiyahM @Keenahn @LijieZhou homework #4, sorry for delay!
Details are in the readme file of the repo.

**Comment by DiyahM** [comment]
Hi @SofyaMulenok 

Really good use of javascript for the rollover affect in your about me section. One non-critical update: consider adding a .gitignore file to remove the .DS_STORE file in your repo. I posted some class notes on .gitignore here https://github.com/hackbrightacademy/pt-frontend-fall-2015/issues/4

Let me know if you have any further questions.
-Diyah
